name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: "Release Version(canary, alpha, beta, latest)"
        required: true
        default: "canary"
        options:
          - canary
          - alpha
          - beta
          - latest
  issue_comment:
    types: [created]

jobs:
  release:
    name: Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # This makes Actions fetch only one branch to release
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install node_modules
        run: |
          npm install -g pnpm@7.25.0
          pnpm -v
          pnpm install
      - name: Build
        run: pnpm run build
      - name: Release
        uses: modern-js-dev/actions@feat-tag-branch
        with:
          # this expects you to have a script called release which does a build for your packages and calls modern publish
          version: ${{ github.event.inputs.version }}
          type: "release"
          branch: ${{ github.ref_name }}
          tools: "modern"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          ONLY_RELEASE_TAG: true

