name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: "Release Version(canary, alpha, beta, latest)"
        required: true
        default: "canary"
        options:
          - canary
          - alpha
          - beta
          - latest
  issue_comment:
    types: [created]

jobs:
  issue_commentd:
    name: Release with commentd
    permissions: write-all
    if: github.event.issue.pull_request && contains(github.event.comment.body, '!snapshot')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # This makes Actions fetch only one branch to release
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install node_modules
        run: |
          npm install -g pnpm@7.25.0
          pnpm -v
          pnpm install
      - name: Build
        run: pnpm run build
      - name: Release
        uses: modern-js-dev/actions@fix-action
        with:
          # this expects you to have a script called release which does a build for your packages and calls modern publish
          version: "canary"
          type: "release"
          branch: ${{ github.ref_name }}
          tools: "modern"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          REF: ${{ github.ref }}
      - name: Get package version
        id: version
        run: |
          comment=1.0.0
          echo "::set-output name=comment::$comment"
      - name: Write a new comment
        uses: peter-evans/create-or-update-comment@v1.4.5
        continue-on-error: true
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ${{ steps.version.outputs.comment }}
  release:
    name: Release
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          # This makes Actions fetch only one branch to release
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install node_modules
        run: |
          npm install -g pnpm@7.25.0
          pnpm -v
          pnpm install
      - name: Build
        run: pnpm run build
      - name: Release
        uses: modern-js-dev/actions@fix-action
        with:
          # this expects you to have a script called release which does a build for your packages and calls modern publish
          version: ${{ github.event.inputs.version }}
          type: "release"
          branch: ${{ github.ref_name }}
          tools: "modern"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          REF: ${{ github.ref }}
